name: Make URLs Active

on:
  schedule:
    - cron: '*/20 * * * *'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Request
        env:
          URLS: ${{secrets.URLS}}
        run: |
          for url in $(echo $URLS | jq -r '.[]'); do
            echo "Sending GET request to $url"
            response=$(curl -s $url)
            echo "Response body:"
            echo "$response"
          done