name: Make URLs Active

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Request
        env:
          URLS: ${{ split('\n', secrets.URLS) }}
        run: |
          for url in $URLS; do
            curl $url
          done
