name: Make URLs Active

on:
  schedule:
    - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Request
        env:
          URLS: '["https://placementcsbhu.onrender.com", "https://google.com"]'
        run: |
          for url in $(echo $URLS | jq -r '.[]'); do
            echo "Sending GET request to $url"
            response=$(curl -s $url)
          done